on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    # Specify OS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --features rgba -- -D clippy::all
      - run: cargo test --features rgba
      - run: cargo publish --token ${CRATES_TOKEN} --features rgba
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}